spring:
  kafka:
    consumer:
      bootstrap-servers: "kafka1:19092,kafka1:29092,kafka1:39092"

kafka:
  topic:
    delivery: "fks.delivery"

server:
  port: 8083

management:
  server:
    port: 9993
  endpoints:
    web:
      exposure:
        include: "info, health, metrics, prometheus"
